# Generated by Django 5.2.7 on 2025-10-15 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Производитель')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='WeaponType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип оружия')),
                ('description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('icon_filename', models.CharField(default='icon-rifle.svg', max_length=50, verbose_name='Имя файла иконки (из static/images/)')),
                ('slug', models.SlugField(default='default-slug', max_length=100, unique=True, verbose_name='URL (slug)')),
            ],
            options={
                'verbose_name': 'Тип оружия',
                'verbose_name_plural': 'Типы оружия',
            },
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('caliber', models.CharField(max_length=50, verbose_name='Калибр')),
                ('fire_rate', models.PositiveIntegerField(verbose_name='Скорострельность (выстр/мин)')),
                ('effective_range', models.PositiveIntegerField(verbose_name='Эффективная дальность (м)')),
                ('image', models.ImageField(upload_to='weapons_images/', verbose_name='Изображение оружия')),
                ('bullet_image', models.ImageField(blank=True, null=True, upload_to='bullets_images/', verbose_name='Изображение патрона')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weapons', to='weapons.manufacturer', verbose_name='Производитель')),
                ('weapon_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weapons', to='weapons.weapontype', verbose_name='Тип оружия')),
            ],
            options={
                'verbose_name': 'Оружие',
                'verbose_name_plural': 'Оружие',
            },
        ),
    ]
