# Generated by Django 5.2.7 on 2025-10-15 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=50, verbose_name="Год или период (напр., 'XV век')")),
                ('title', models.CharField(max_length=200, verbose_name='Название эпохи')),
                ('description', models.TextField(verbose_name='Описание эпохи')),
                ('era_image', models.ImageField(blank=True, null=True, upload_to='history_images/', verbose_name='Фоновое изображение для карточки')),
            ],
            options={
                'verbose_name': 'Историческая эпоха',
                'verbose_name_plural': 'Исторические эпохи',
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalWeapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название оружия')),
                ('description', models.TextField(verbose_name='Краткая история')),
                ('weapon_image', models.ImageField(upload_to='history_images/', verbose_name='Изображение оружия')),
                ('era', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_weapons', to='weapons.historicalera', verbose_name='Эпоха')),
            ],
            options={
                'verbose_name': 'Историческое оружие',
                'verbose_name_plural': 'Историческое оружие',
            },
        ),
    ]
