# Generated by Django 5.2.7 on 2025-10-15 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0002_historicalera_historicalweapon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalera',
            options={'ordering': ['sort_order'], 'verbose_name': 'Историческая эпоха', 'verbose_name_plural': 'Исторические эпохи'},
        ),
        migrations.AddField(
            model_name='historicalera',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='Порядок сортировки (чем меньше, тем раньше)'),
        ),
    ]
