# Generated by Django 5.2.7 on 2025-10-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0004_newsarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='model_path',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Путь к 3D модели (от папки static)'),
        ),
    ]
