# Generated by Django 5.2.7 on 2025-10-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0005_weapon_model_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('armament', models.TextField(verbose_name='Вооружение')),
                ('max_speed', models.PositiveIntegerField(verbose_name='Макс. скорость (км/ч)')),
                ('ceiling', models.PositiveIntegerField(verbose_name='Практический потолок (м)')),
                ('image', models.ImageField(upload_to='aircraft_images/', verbose_name='Изображение')),
                ('model_path', models.CharField(blank=True, max_length=200, null=True, verbose_name='Путь к 3D модели (от папки static)')),
            ],
            options={
                'verbose_name': 'Летательный аппарат',
                'verbose_name_plural': 'Летательные аппараты',
            },
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('main_armament', models.CharField(max_length=100, verbose_name='Основное вооружение')),
                ('armor', models.CharField(max_length=100, verbose_name='Броня (мм)')),
                ('max_speed', models.PositiveIntegerField(verbose_name='Макс. скорость (км/ч)')),
                ('image', models.ImageField(upload_to='tanks_images/', verbose_name='Изображение')),
                ('model_path', models.CharField(blank=True, max_length=200, null=True, verbose_name='Путь к 3D модели (от папки static)')),
            ],
            options={
                'verbose_name': 'Танк',
                'verbose_name_plural': 'Танки',
            },
        ),
    ]
